# This manifest configures the Swift Package Index to generate and host DocC
# documentation.
#
# See https://swiftpackageindex.com/swiftpackageindex/spimanifest/documentation/spimanifest/commonusecases

version: 1
builder:
  configs:
    - documentation_targets:
      # First item in the list is the "landing" (default) target
      - SnapshotTesting
      - SnapshotPreviews
      - InlineSnapshotTesting
    - platform: watchos
      scheme: InlineSnapshotTesting
