name: CI

on:
  pull_request:

jobs:
  macos:
    name: macOS
    runs-on: blacksmith-6vcpu-macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 26.4.1
        run: sudo xcode-select -s /Applications/Xcode_26.4.1.app
      - name: Run tests
        run: make test-swift

  ubuntu:
    container: swift:6.3
    name: Linux (Swift 6.3)
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - run: swift test

  android:
    name: Android
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: skiptools/swift-android-action@v2
        with:
          swift-version: "6.3"
          copy-files: ${GITHUB_WORKSPACE}/Tests/SnapshotTestingTests/__Snapshots__
